In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
import plotly.express as px
from matplotlib import pyplot as plt 
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('clothing_reviews_clean_with_features.csv')

In [4]:
df.head(3)

,Unnamed: 0,review,recommended,age,class,department,length,polarity,lower,no_punc,no_stop,no_num,words_removed,token,pos_tags,lemmatized
0,0,Absolutely wonderful - silky and sexy and comf...,1,33,Intimates,Intimate,53,0.633333,absolutely wonderful - silky and sexy and comf...,absolutely wonderful silky and sexy and comfo...,absolutely wonderful silky sexy comfortable,absolutely wonderful silky sexy comfortable,absolutely wonderful silky sexy comfortable,"['absolutely', 'wonderful', 'silky', 'sexy', '...","[('absolutely', 'RB'), ('wonderful', 'JJ'), ('...","['absolutely', 'wonderful', 'silky', 'sexy', '..."
1,1,Love this dress! it's sooo pretty. i happene...,1,34,Dresses,Dresses,303,0.339583,love this dress! it's sooo pretty. i happened ...,love this dress its sooo pretty i happened to ...,love dress sooo pretty happened find store im ...,love dress sooo pretty happened find store im ...,love sooo pretty happened find store glad bc n...,"['love', 'sooo', 'pretty', 'happened', 'find',...","[('love', 'VB'), ('sooo', 'NN'), ('pretty', 'R...","['love', 'sooo', 'pretty', 'happen', 'find', '..."
2,2,I had such high hopes for this dress and reall...,0,60,Dresses,Dresses,500,0.073675,i had such high hopes for this dress and reall...,i had such high hopes for this dress and reall...,high hopes dress really wanted work initially ...,high hopes dress really wanted work initially ...,high hopes really wanted work initially ordere...,"['high', 'hopes', 'really', 'wanted', 'work', ...","[('high', 'JJ'), ('hopes', 'NNS'), ('really', ...","['high', 'hope', 'really', 'want', 'work', 'in..."

In [6]:
analysis_df = df[['lemmatized', 'recommended', 'age', 'class', 'department', 'length']]